# Generated by Django 5.2.4 on 2025-07-29 11:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=50, verbose_name='Nom complet')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Téléphone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appdatascience.role')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Identifiant unique de la transaction', max_length=20, unique=True, verbose_name='Référence')),
                ('type', models.CharField(choices=[('CASH_IN', 'Dépôt'), ('CASH_OUT', 'Retrait'), ('TRANSFER', 'Transfert'), ('PAYMENT', 'Paiement'), ('DEBIT', 'Prélèvement')], default='CASH_OUT', max_length=10, verbose_name='Type')),
                ('step', models.PositiveSmallIntegerField(help_text='Heure de la transaction (en heures)', verbose_name='Heure')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Date enregistrement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('oldbalanceOrg', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde initial origine')),
                ('newbalanceOrig', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Nouveau solde origine')),
                ('oldbalanceDest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Solde initial destination')),
                ('newbalanceDest', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Nouveau solde destination')),
                ('result_predicted', models.CharField(choices=[('FRAUD', 'Fraude'), ('LEGIT', 'Légitime'), ('SUSPICIOUS', 'Suspect'), ('PENDING', 'En attente')], default='PENDING', max_length=10, verbose_name='Résultat prédit')),
                ('confidence_score', models.FloatField(blank=True, help_text='Probabilité de fraude (0-1)', null=True, verbose_name='Score de confiance')),
                ('is_verified', models.BooleanField(default=False, help_text='Transaction validée par un agent', verbose_name='Vérifiée')),
                ('fraud_flag_reason', models.TextField(blank=True, help_text='Explication du marquage comme fraude', verbose_name='Raison du flag')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_recues', to=settings.AUTH_USER_MODEL, verbose_name='Compte destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Compte origine')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_enregistrement'],
                'indexes': [models.Index(fields=['reference'], name='appdatascie_referen_fd8bf8_idx'), models.Index(fields=['type'], name='appdatascie_type_a8ea45_idx'), models.Index(fields=['result_predicted'], name='appdatascie_result__e8ef0a_idx'), models.Index(fields=['origin', 'date_enregistrement'], name='appdatascie_origin__afca5a_idx')],
            },
        ),
    ]
