# Generated by Django 5.2.4 on 2025-07-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appdatascience', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
