# Generated by Django 5.2.4 on 2025-08-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdatascience', '0003_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Solde'),
        ),
    ]
